version: "3.8"

services:
  database:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - ~/pg_data:/var/lib/postgresql/data
    networks:
      - backend
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "$DB_USER", "-d", "$DB_NAME"]
      interval: 10s
      timeout: 5s
      retries: 5

  server:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      database:
        condition: service_healthy
    networks:
      - backend
    ports:
      - "8080:8080"

networks:
  backend:
    driver: bridge