db:
  name: dbname
  user: dev
  password: 123456
  port: 5432
  host: 127.0.0.1

kafka:
  address: localhost:9092
  topic: notifications

# DEBUG
# INFO
# WARN
# ERROR
# PANIC
# PANIC
# FATAL
logger:
  level: DEBUG

server:
  port: 8080
